### ISSUE TITLE
Weird Import

### ISSUE THREAD

**Issue by Inffinite** [Jebasuthan/Vue-Facebook-Google-oAuth#1]
Whats does this line do. it doesn't make sense.

`import GoogleAuth from '@/config/google.js'`

**Comment by Jebasuthan** [comment]
> Whats does this line do. it doesn't make sense.
> 
> `import GoogleAuth from '@/config/google.js'`

Hi @Inffinite, Import file name correction in readme file. Corrected the import file name.

>` import GoogleAuth from '@/config/google_oAuth.js'`
